### ISSUE TITLE
Enhancement: Animals animation & Interaction

### ISSUE THREAD

**Issue by Hermestt** [Hermestt/Hermestt.github.io#2]
#### Description
To visually enhance header and the interactivity with the webpage, I want to animate the animals image, and the blue ball behind, to have a subtle animation (floating up and down) and some sort of **indication that it is a clicable component**.  This last part is important for mobile visitors.

#### Requirements
When the user clicks on the animal, the random number generator responsible to get the new animal cannot generate the same animal as it is active in the moment, it HAS to be different.

#### Tasks
- [x] Add CSS animation to the components and its items;
- [x] Add the interaction indicator;
- [x] Rewrite the JS code to be the best version I can do;
- [x] Test;

**Comment by Hermestt** [comment]
Additional tasks solved during the process

- [x] changed position of element containers (better readability, user conduction and remove avoidable css "over-attribute"
- [x] removed heigh by vh from header section, it crashes on bigger screens (>1920), now it works by the section below applying a margin-top from 15% over 600px viewport and 40% below.
- [x] Added more animals and updated owl
- [x] Updated README.md removing the improvement list in order to create issues for each one.
